Get cmake generator from environment in windows for lockfile example
conan-io/examples pull request #70
Opened 2020-08-27 07:23 UTC by czoido

2020-08-28 16:23 UTC, jgsogo approved these changes

2020-08-28 16:24 UTC, jgsogo requested changes
Wait! Maybe we should use a default value, or do something that lets the user know what is happening

2020-08-30 21:17 UTC, memsharded commented
> I think we should get the value, check it exists, and if it doesn't we can write a message to the user: populate this environment variable with your generator before calling this example... or add only the -G xxxxx if the variable exists (I don't know if CMake will choose an existing VS generator by default)

Yes, the -G cmake generator is generally necessary in Windows. It is necessary to add something in the script, that will fail if not defined and force to define it, otherwise it is very confusing for the user.

2020-09-01 12:55 UTC, jgsogo approved these changes
🙌  Really cool to see examples green again!

Thanks!

2020-09-01 12:55 UTC, merged

2020-09-30 00:15 UTC, Featzaza999 reviewed
cmake $ GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE = $ BUILD_TYPE

2020-09-30 00:16 UTC, Featzaza999 commented on .ci/run.py
> +            './features/lockfiles/build_order', # new lockfiles version
``